# Generated by Django 4.1.7 on 2023-03-03 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 16, 35, 45, 43413), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department', verbose_name='Кафедра'),
        ),
    ]
