# Generated by Django 4.1.7 on 2023-02-28 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 20, 54, 9, 481202), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='time_1',
            field=models.IntegerField(default=0, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='time_2',
            field=models.IntegerField(default=0, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='time_3',
            field=models.IntegerField(default=0, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='time_4',
            field=models.IntegerField(default=0, verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='time_5',
            field=models.IntegerField(default=0, verbose_name='5'),
        ),
    ]
