# Generated by Django 4.1.7 on 2023-03-25 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_date_alter_group_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 12, 2, 22, 177120), verbose_name='Дата'),
        ),
    ]
